language: node_js
node_js:
  - 6
env:
  global:
    - CXX=g++-4.8
  matrix:
    - NPM_COMMAND=lint
    - NPM_COMMAND=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
script: npm run $NPM_COMMAND
